# Default values for simple-web.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: acrinterview.azurecr.io/simple-web
  pullPolicy: IfNotPresent
  tag: latest

service:
  name: simple-web
  namespace: josh
  port: 80
  type: ClusterIP

ingress:
  enabled: true
  name: simple-web-ingress
  host: 20.86.195.36
  path: /josh
  pathType: Prefix

nodeSelector: {}

tolerations: []

affinity: {}

serviceAccount:
  create: true

