# Default values for simple-web.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

autoscaling:
  enabled: false

image:
  repository: acrinterview.azurecr.io/simple-web
  pullPolicy: IfNotPresent
  tag: latest

service:
  name: simple-web
  namespace: josh
  port: 80
  type: ClusterIP

ingress:
  enabled: true
  name: simple-web-ingress
  host: devops-interview-me10b2tr.hcp.westeurope.azmk8s.io
  path: /josh
  pathType: Prefix

nodeSelector: {}

tolerations: []

affinity: {}

serviceAccount:
  create: true

