# Default values for simple-web.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: acrinterview.azurecr.io/simple-web
  pullPolicy: IfNotPresent
  tag: latest

apiVersion: v1
kind: Service
metadata:
  name: simple-web
  namespace: josh
spec:
  selector:
    app: simple-web
  ports:
  - name: http
    port: 80
    targetPort: 80
  type: LoadBalancer

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: example.com
      paths:
      - path: /josh
        backend:
          serviceName: LoadBalancer
          servicePort: 80

keda:
  enabled: true
  scalers:
    - type: pods
      metadata:
        name: simple-web
      pollingInterval: 5
      cooldownPeriod: 5
      triggers:
        - type: cpu
          metadata:
            query: "sum(container_cpu_usage_seconds_total) / sum(machine_cpu_cores) * 100"
            threshold: "80"
        - type: memory
          metadata:
            query: "sum(container_memory_working_set_bytes) / sum(machine_memory_bytes) * 100"
            threshold: "80"
  scaledObject:
    metadata:
      name: simple-web
    spec:
      scaleTargetRef:
        name: simple-web
        kind: Deployment
      minReplicaCount: 1
      maxReplicaCount: 5
      cooldownPeriod: 5
      pollingInterval: 5
      triggers:
        - type: schedule
          metadata:
            timezone: "Asia/Jerusalem"
            startTime: "08:00"
            endTime: "12:00"
            interval: "1h"

nodeSelector: {}

tolerations: []

affinity: {}

serviceAccount:
  create: true

