# Default values for simple-web.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

autoscaling:
  enabled: false

image:
  repository: acrinterview.azurecr.io/simple-web
  pullPolicy: IfNotPresent
  tag: latest

service:
  name: simple-web
  namespace: josh
  port: 80
  type: ClusterIP

ingress:
  enabled: true
  name: simple-web-ingress
  path: /josh
  pathType: Prefix
  annotations:
    kubernetes.io/ingress.class: nginx


autoscaling:
  enabled: true
  type: keda
  minReplicas: 3
  maxReplicas: 6
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
  schedule:
    enabled: true
    desiredReplicas: 4
    start: "0 8 * * *"
    end: "0 12 * * *"

nodeSelector: {}

tolerations: []

affinity: {}

serviceAccount:
  create: true

