apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "simple-web.fullname" . }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            backend:
              serviceName: {{ include "simple-web.fullname" . }}
              servicePort: {{ .Values.service.port }}
