apiVersion: v1
kind: Service
metadata:
  name: {{ include "simple-web.fullname" . }}
  namespace: josh
  labels:
    app: {{ include "simple-web.name" . }}
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      name: http
  selector:
    app: {{ include "simple-web.name" . }}
